### ISSUE TITLE
Sunder Armor not triggering Chance on Hit

### ISSUE THREAD

**Issue by YoshGit** [elysium-project/server#1011]
Copy paste from Elysium Forum: https://forum.elysium-project.org/topic/48239-ironfoe-testing/

> Anyone` who knows me in game knows that Ironfoe is my baby. You would also know that I have garbage luck when it comes to getting new weapons. Because of this, I was pretty much looking for any reason to justify using the hammer over any other weapon, so I did some digging and testing. This is what I found...
> 
> - The` Elysium database (SQL file available on github) has Ironfoe's ppm at 1.5, ie 6% proc chance.
> 
>   Quote
> (11684,2,4,'Ironfoe',23618,4,0,1,315430,63086,21,-1,-1,60,55,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,73,136,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2400,0,0,15494,2,0,1.5,-1,...
> 
> 15494 is the spell id, 1.5 is the ppm, -1 shows no cool down. I tested this extensively with a sample size of 2000+ auto attacks (hits/crits/blocks only), no HOJ, hit capped, no dual wield, white hits only, and got a proc chance of 5.4% with a 95% confidence interval of about 1. A 6% proc rate seems realistic. 
> 
>  
> 
> - Extra attack procs cannot proc extra attack procs.
> 
>   Quote
> // not allow proc extra attack spell at extra attack if (m_extraAttacks && IsSpellHaveEffect(triggerEntry, SPELL_EFFECT_ADD_EXTRA_ATTACKS) && triggerEntry->Id != 20178) return SPELL_AURA_PROC_FAILED;
> 
> Other similar code snippets appear all over the place. During all of my testing I never saw a "chain-proc." Its probably safe to assume that proc like HOJ and Thrash Blade also fit under this category. Most people already know this.
> 
>  
> 
> - Sunder Armor does not proc Ironfoe (havent tested with other chance-on-hit items)
> 
> After running ZG today, I noticed my Ironfoe procs were very low considering I was getting over 5% proc rates during tests the same day. I tested Ironfoe using only sunder armor (pooled rage, and canceled auto attacks before and after casting sunders). While using only sunder (no white hits went through), I got zero procs after about 200 sunders. Bad luck can be eliminated as a factor with this sample size and explains the weapon's poor performance in ZG. This is a huge detriment for tanks using Ironfoe for TPS since it is your most used ability. Since sunder armor requires a weapon, this is likely due to the fact that it deals no damage and is probably a bug.
> 
>  
> 
>  
> 
> -Bloodthirst does not proc Ironfoe (havent tested with other chance-on-hit items)
> 
> Same as Sunder Armor, but I only gathered a sample size of about 70. Extremely small chance that this was just bad luck assuming even a 5% proc rate, but this actually makes sense since Bloodthrist doesn't require a weapon to cast.
> 
>  
> 
> - Hamstring procs Ironfoe confirmed.
> 
> - Whirlwind procs Ironfoe confirmed.
> 
> - HS, Cleave, Execute, and Overpower probably proc Ironfoe based on intuition and experience, but yet to be tested.
> 
>  
> 
> Conclusion: Nothing too new in the grand scheme of things. The proc rate is probably higher than we expected, but also doesn't proc off of all of our yellow hits. As fury, Ironfoe is still pretty good but are probably outclassed by BWL weapons (until maybe Anubisath Warhammer for humans/dwarves). As a tank, Sunder Armor not procing Ironfoe discounts its value, and is probably a bug (need proof on whether sunder procs chance-on-hit in retail).
>

**Comment by hckYosh** [comment]
Noticed that similar fixes have been proposed but denied. A similar fix should resolve this problem. Still looking for indisputable evidence that SA triggers main hand weapon procs. 

(Also, a lot of people are complaining that TF is undertuned when the ppm seams reasonable. Issues regarding SA and Shield Slam not triggering main hand procs is likely the culprit)

[https://github.com/elysium-project/server/pull/187](url)

**Comment by hckYosh** [comment]
Found evidence that Sunder Armor indeed triggers main hand procs.

7:12 - The warrior uses Sunder Armor, auto attack was dodged, Thunderfury procs.

https://www.youtube.com/watch?v=hGewOCCa1_A

**Comment by Ixl-DS** [comment]
Ironfoe still can't proc from Sunder Armor.
Tested for a couple of hours, 0 proc.
