### ISSUE TITLE
Bugged AV Quest rewards

### ISSUE THREAD

**Issue by hazcow** [elysium-project/server#1576]
I picked up the quest "The Legend of Korrak" and the only reward available is the "Rune of Recall", but it is also suppose to include the ice barbed spear, bloodseeker, and wand of biting cold. Additionally, the quest "Hero of Frostwolf" is not even showing up after completing the quest "The Battle for Alterac". The "Hero of Frostwolf" rewards you with the ice barbed spear, bloodseeker, wand of biting cold, or the cold forged hammer. Were these items/quests removed from the game after the last update? Or is this just a bug?

**Comment by Dummestork** [comment]
I got the same problem. I have just turned in "The Battle for Alterac", but no follow up with "Hero of The Frostwolf Clan" is available.
Asking in chat, confirms that the quest has been available recently, maybe the new patch today bugged it?

**Comment by thepparker** [comment]
Accidentally removed in the last patch, returning shortly

**Comment by FireReaver** [comment]
Yes, problem is still there. Hope it will be fixed sooner or later.

**Comment by Dummestork** [comment]
Was fixed a day after I wrote. Looks like its bugging with every server restart.

**Comment by hazcow** [comment]
The "Battle of Alterac" quest was available the day after I started this thread, so I was able to get the cold forged hammer. But the "Legend of Korrak" quest still does not display all of the rewards (as listed online) only the "Rune of Recall".

**Comment by thepparker** [comment]
Due to a mishap in the original deployment of 1.5 on Elysium and the Korrak rewards, we opted to add the "Hero of the Frostwolf"/"Hero of the Stormpike" quests earlier, with the associated rewards. The Korrak quest no longer rewards the items, much the same as retail once blizzard introduced the aforementioned quests.
