### ISSUE TITLE
(Anathema) Twilight Cultist Items

### ISSUE THREAD

**Issue by Drabic** [elysium-project/server#2790]
Parts of Twilight set for summon bosses in silithus not drop from mobs, i am farm mobs 2hours & not drip anyone item

**Comment by GuybrushGit** [comment]
Server

**Comment by QAkvastskaft** [comment]
see: #2665

**Comment by Weywu** [comment]
The Twilight Text's and Cultist items are still not dropping

just a bump up

**Comment by GuybrushGit** [comment]
Fixed with https://github.com/elysium-project/server/pull/2972

**Comment by tacodoctor** [comment]
This is still an issue and has not been fixed. Only prophet appears to drop twilight texts, have not seen any of the items drop from any of the mobs they are supposed to after about 1/2 and hour of trying.
