### ISSUE TITLE
Crabs standing on seabed are perma-rooted, enter evade mode if attacked from outside melee range

### ISSUE THREAD

**Issue by Unknown-as-Captain** [elysium-project/server#413]
Priority: Low

BUGGED BEHAVIOR: https://www.youtube.com/watch?v=OSKzigrcRxE
Crab gets "stuck" and is unable to move away from the spot where he was pulled. If the crab cannot reach the player from that one spot, he enters evade mode and regenerates health quickly.
The crab can thus only be killed from melee range. This is kinda problematic for ranged classes like mages.

Eliminating factors that could cause this bug:
Video 1 shows that the bug is not related to the player being swimming. Crab still cannot path to player even when the player moves to land.
Video 2: https://www.youtube.com/watch?v=dm7reDdlEMU
Crabs on land never get affected by this bug from what I can tell, they are able to chase players into the water. Crabs that are underwater, but only in shallow water also do not get affected.

Seems to be some kind of pathing problem when a mob is "standing" on deep seabed. However, I later found this non-crab mob that seemed to also be "standing" on deep seabed, and they could path to me successfully: https://www.youtube.com/watch?v=HSB3z1N-zrU

Mobs confirmed to show this bug (only while deep underwater):
http://db.vanillagaming.org/?npc=922
http://db.vanillagaming.org/?npc=3107
http://db.vanillagaming.org/?npc=3106
http://db.vanillagaming.org/?npc=1088

**Comment by sknnbones** [comment]
It seems some mobs will randomly enter evade bug as well.

Its rather random, I'll usually come across a mob not pathing and AOE doesnt work, traps don't trigger, pet commands say "invalid target" 

After a few minutes the bugged enemies sometimes just disappear.

**Comment by Unknown-as-Captain** [comment]
Was manually fixed in all 4 mobs listed via https://github.com/elysium-project/server/pull/421/files#diff-e248e0a4f436002d0a19b6823daf9beb

The list given was not exhaustive, if more crabs that hit rock bottom are later found, same fix should be applied to them

**Comment by staplerx300** [comment]
https://streamable.com/t0cju

bump, its still an issue with all the crabs in darkshore, im assuming the crawlers in senjin village as well but havnet confirmed
